# Make sure to check the documentation at http://goreleaser.com
project_name: http-over-ssh

before:
  hooks:
  - go mod download

builds:
- goos:   [linux, freebsd, windows, darwin]
  goarch: [amd64, arm64]
  env:
  - CGO_ENABLED=0

release:
  prerelease: auto

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort:       asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^ci:'
